Refactor Terraform Apply step and remove unnecessary app setting

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -129,15 +129,11 @@ jobs:
     # Terraform Apply
     - name: Terraform Apply
       id: tf-apply
-      run: terraform apply -auto-approve tfplan | tee apply_output.txt || export exitcode=$?
-
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-        
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Apply Failed!
+      run: |
+        terraform apply -auto-approve tfplan | tee apply_output.txt
+        if [ ${PIPESTATUS[0]} -ne 0 ]; then
+          echo "Terraform Apply failed."
           exit 1
-        else 
-          exit 0
         fi
       working-directory: ./terraform
 
